version: '3.1'
services:
  php:
    image: 'php:background'
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    ports:
      - '80:80'
    volumes:
      - './src/:/var/www/html/'
networks:
  default:
    external:
      name: ngswarm
