version: '3.1'
services:
 mysql:
  image: 'db:custom'
  deploy:
      placement:
        constraints:
          - node.role == worker
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=TASK
networks:
  default:
    external:
      name: ngswarm
